-- Per-agent AI control

ALTER TABLE agents ADD COLUMN IF NOT EXISTS tick_interval_ms INTEGER NOT NULL DEFAULT 1500;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS llm_probability REAL NOT NULL DEFAULT 0.4;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS ai_model TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS system_prompt TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS next_tick_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
